databases:
  - name: backend-project-6-db
    databaseName: backend_project_6
    user: backend_project_6
    plan: free

services:
  - type: web
    name: backend-project-6
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: backend-project-6-db
          property: connectionString
      - key: ROLLBAR_ACCESS_TOKEN
        sync: false
